// Generated by https://quicktype.io

export interface ResponseElementos {
    componentes: ComponenteElemento[];
}

export interface ComponenteElemento {
    componente:   string;
    id_elemento:  string;
    descripcion:  string;
    id_solicitud: number | null ;
}


