// Generated by https://quicktype.io

import { OrdenMetrics } from "./ResponseOrdenMetrics";



export interface ResponseElementos {
    componentes: ComponenteElemento[];
    orden :OrdenMetrics,
    
}

export interface ComponenteElemento {
    componente:   string;
    id_elemento:  string;
    descripcion:  string;
    id_solicitud: number | null ;
}


